name: Ruby

on: [push,pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.1
    - name: build
      run: |
        gem install bundler
        bundle install
    - name: lint
      run: bundle exec rubocop
    - name: test
      run: bin/test
